#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python  /app/manage.py migrate
python /app/manage.py collectstatic --noinput

/usr/local/bin/gunicorn settings.asgi -c gunicorn.conf.py --chdir=/app  -k uvicorn.workers.UvicornWorker

