# Generated by Django 4.0.5 on 2022-06-07 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('region', models.IntegerField(verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filials',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='FilialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.filial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'FilialPrice',
                'verbose_name_plural': 'FilialPrices',
            },
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('self', models.AutoField(primary_key=True, serialize=False, verbose_name='self')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('product', models.ManyToManyField(to='catalog.product')),
            ],
            options={
                'verbose_name': 'Characteristic',
                'verbose_name_plural': 'Characteristics',
            },
        ),
    ]
